### PR TITLE
K3s selinux rpm changes

### LINKED ISSUE #565: Updating a package already installed fails if the package vendor is different
In this particular case it affects k3s-selinux update needed for the fixes included in 1.6 and only available on the k3s repos https://rpm.rancher.io/k3s/stable/common/slemicro/noarch.

More details:

SL Micro 6 includes k3s-selinux 1.4 with vendor SUSE:

```
Information for package k3s-selinux:
------------------------------------
Repository     : @System
Name           : k3s-selinux
Version        : 1.4.stable.1-1.5
Arch           : noarch
Vendor         : SUSE LINUX Products GmbH, Nuernberg, Germany
Installed Size : 94.9 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : k3s-selinux-1.4.stable.1-1.5.src
Upstream URL   : http://k3s.io/k3s-selinux
Summary        : SELinux policy module for k3s
Description    :
    This package installs and sets up the SELinux policy security module for k3s.
```

However the updated k3s-selinux from https://rpm.rancher.io/k3s/stable/common/slemicro/noarch the vendor is not SUSE:

```
Information for package k3s-selinux:
------------------------------------
Repository     : @System
Name           : k3s-selinux
Version        : 1.6-1.slemicro
Arch           : noarch
Vendor         :
Installed Size : 95.0 KiB
Installed      : Yes
Status         : up-to-date
Source package : k3s-selinux-1.6-1.slemicro.src
Upstream URL   : https://k3s.io/
Summary        : SELinux policy module for k3s
Description    :
    This package installs and sets up the SELinux policy security module for k3s.
```

So zypper complains when trying to update that package:

```
Sep 17 12:46:22 host1rke2 combustion[1579]: There is an update candidate for 'k3s-selinux' from vendor '', while the current vendor is 'SUSE LINUX Products GmbH, Nuernberg, Germany'. Use >m vendor '', while the current vendor is 'SUSE LINUX Products GmbH, Nuernberg, Germany'. Use 'zypper install k3s-selinux-1.6-1.slemicro.noarch' to install this candidate.
```

However zypper supports using a special `--allow-vendor-change` flag that disables this behavior (more info https://en.opensuse.org/SDB:Vendor_change_update)

Longterm I guess we should ship the fixed version OOTB or at least pull it from the proper sources instead of upstream.

### PR DESCRIPTION
**Pull request by dbw7**
Closes #565

### CODE REVIEW

File: pkg/kubernetes/selinux.go [hunk 1]
```diff
@@ -10,10 +10,10 @@ import (
 	"github.com/suse-edge/edge-image-builder/pkg/image"
 )
 
-func SELinuxPackage(version string) (string, error) {
-	const (
-		k3sPackage  = "k3s-selinux"
-		rke2Package = "rke2-selinux"
+func SELinuxPackage(version string, sources *image.ArtifactSources) (string, error) {
+	var (
+		k3sPackage  = sources.Kubernetes.K3s.SelinuxPackage
```
Comment (atanasdinov) [inline pkg/kubernetes/selinux.go:15]: Just use the value directly, there's no point in setting these variables anymore.

File: pkg/kubernetes/selinux.go [hunk 2]
```diff
@@ -26,10 +26,10 @@ func SELinuxPackage(version string) (string, error) {
 	}
 }
 
-func SELinuxRepository(version string) (image.AddRepo, error) {
-	const (
-		k3sRepository  = "https://rpm.rancher.io/k3s/stable/common/slemicro/noarch"
-		rke2Repository = "https://rpm.rancher.io/rke2/stable/common/slemicro/noarch"
+func SELinuxRepository(version string, sources *image.ArtifactSources) (image.AddRepo, error) {
+	var (
+		k3sRepository  = sources.Kubernetes.K3s.SelinuxRepository
```
Comment (atanasdinov) [inline pkg/kubernetes/selinux.go:31]: Same as above.

File: pkg/image/context.go [hunk 3]
```diff
@@ -39,4 +39,14 @@ type ArtifactSources struct {
 		RegisterRepository    string `yaml:"register-repository"`
 		SystemAgentRepository string `yaml:"system-agent-repository"`
 	} `yaml:"elemental"`
+	Kubernetes struct {
+		K3s struct {
+			SelinuxPackage    string `yaml:"selinuxPackage"`
+			SelinuxRepository string `yaml:"selinuxRepository"`
```
Comment (atanasdinov) [inline pkg/image/context.go:45]: Nit:
```suggestion
			SELinuxPackage    string `yaml:"selinuxPackage"`
			SELinuxRepository string `yaml:"selinuxRepository"`
```

File: pkg/image/context.go [hunk 4]
```diff
@@ -39,4 +39,14 @@ type ArtifactSources struct {
...
+		} `yaml:"k3s"`
+		Rke2 struct {
+			SelinuxPackage    string `yaml:"selinuxPackage"`
+			SelinuxRepository string `yaml:"selinuxRepository"`
```
Comment (atanasdinov) [inline pkg/image/context.go:49]: Nit:
```suggestion
			SELinuxPackage    string `yaml:"selinuxPackage"`
			SELinuxRepository string `yaml:"selinuxRepository"`
```

File: RELEASE_NOTES.md [hunk 5]
```diff
@@ -4,6 +4,8 @@
 
 ## General
 
+* Extracted the K3S and RKE2 package and repository definitions into artifacts.yaml
```
Comment (atanasdinov) [inline RELEASE_NOTES.md:7]:
```suggestion
* Extracted the K3S and RKE2 SELinux package and repository definitions into artifacts.yaml
```

**Review by atanasdinov — APPROVED** [review]
