### PR TITLE
Modify Helm backOffLimit

### LINKED ISSUE #504: Add backoff limit for helm charts
When creating a HelmChart resource we should specify a backoff limit. This value corresponds to the max number of retries in case the installation is unsuccessful. The default value is 1000(!) which means the installation job would have to exit with an error 1000 times before it is considered failed.

Reference: https://docs.k3s.io/helm#helmchart-field-definitions

### PR DESCRIPTION
**Pull request by dbw7**
Closes #504

### CODE REVIEW

File: pkg/registry/helm_crd.go [hunk 1]
```diff
@@ -53,12 +54,14 @@ func NewHelmCRD(chart *image.HelmChart, chartContent, valuesContent, repositoryU
...
 			TargetNamespace string `yaml:"targetNamespace,omitempty"`
 			CreateNamespace bool   `yaml:"createNamespace,omitempty"`
+			BackOffLimit    int    `yaml:"backOffLimit"`
 		}{
 			Version:         chart.Version,
 			ValuesContent:   valuesContent,
 			ChartContent:    chartContent,
 			TargetNamespace: chart.TargetNamespace,
 			CreateNamespace: chart.CreateNamespace,
+			BackOffLimit:    20,
```
Comment (atanasdinov) [inline pkg/registry/helm_crd.go:64]: Can we extract this as a const?

**Review by atanasdinov — APPROVED** [review]

**Review by atanasdinov — APPROVED** [review]
